### ISSUE TITLE
el "Autentica" funciona?

### ISSUE THREAD

**Issue by morodrigo** [lunasoft/sw-descargamasiva-php#3]
Buenas Tardes.
Descarge tu contribución, estuve revisando, sin embargo me regresa un error al intentar autenticar **"An error occurred when verifying security for the message."**, el certificado no es problema por que lo adjunto tal y como está,  la llave, la estoy convirtiendo a .pem, con: **"openssl pkcs8 -inform DER -in ruta_key -out ruta_donde_se_gaurda.pem -passin pass:elpass"**

Pudiera ser algún error ? o que me recomiendas probar.

**Comment by morodrigo** [comment]
Tenia una problema con el pem, si funciona,muchas gracias,.

**Comment by nmovazquez** [comment]
> Tenia una problema con el pem, si funciona,muchas gracias,.

Me podrias compartir como los resolviste por favor?
